### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by amainyebriggs** [Rich5/Harness#1]
please a least post a wiki or a video ttutorial thanks kind of setup the listener but dont know how to generate the   selfsigned.cert    selfsigned.key

**Comment by Rich5** [comment]
http://frogstarworldc.com/2015/10/harness-intro-and-usage-guide/

**Comment by Rich5** [comment]
There are also many many tutorials online about creating self signed certs. Hope that helps.

**Comment by amainyebriggs** [comment]
ok thanks
