### ISSUE TITLE
I have this problem: "ImportError: No module named '_ssl'

### ISSUE THREAD

**Issue by lgcambero** [Rich5/Harness#4]

**Comment by Rich5** [comment]
Can you post what commands you were trying when you got the error, and the full Python Error?

**Comment by Rich5** [comment]
Also what version of Python are you using?

**Comment by lgcambero** [comment]
Thanks for answering

wget http://python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz
tar xf Python-3.4.3.tar.xz
cd Python-3.4.3
./configure --prefix=/usr/local --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
make && make altinstall

cd /Harness
python3.4 harness.py

"ImportError: No module named '_ssl'

![screenshot from 2015-12-01 12 13 08](https://cloud.githubusercontent.com/assets/11602705/11508143/356a41b6-9825-11e5-9aca-bde93ce5ee53.png)

**Comment by Rich5** [comment]
ok looks like a Python install problem on Kali 2.0. I'll see if I can recreate.

**Comment by lgcambero** [comment]
I remain waiting for your response

**Comment by Rich5** [comment]
It's be a few minutes. I have to stand up a fresh Kali 2.0 instance. In the mean time try typing this to see if you get the same error:

python3.4
import ssl

**Comment by lgcambero** [comment]
:(
![screenshot from 2015-12-01 12 29 41](https://cloud.githubusercontent.com/assets/11602705/11508560/6e6c3904-9827-11e5-8ffa-ac2937217743.png)

**Comment by Rich5** [comment]
Ok so it's definitely a Python install error. I'll troubleshoot and get back to you.

**Comment by Rich5** [comment]
Try this:
apt-get install libssl-dev openssl

Then:
run the python_install.sh again

It seems to fix the problem for me, but I also noticed that tab completion isn't working on Kali 2.0. I'll open that as a separate issue. Let me know if this fixes your issue.

**Comment by lgcambero** [comment]
It was solved, thanks for the quick response. In a few hours I'll try it and then invite you to see the video tutorial on my channel https://www.youtube.com/c/luiscambero. Cheers!!
![screenshot from 2015-12-01 13 57 20](https://cloud.githubusercontent.com/assets/11602705/11510913/059f99e0-9834-11e5-8371-1dc550b6e4bd.png)

**Comment by Rich5** [comment]
Great! I figured out the autocomplete issue also. I'll post in a separate issue an update the install script in a later update
